### ISSUE TITLE
Error while running script on Windows 11 ARM

### ISSUE THREAD

**Issue by AGitUser0001** [ThioJoe/Windows-Super-God-Mode#8] opened 2024-08-25 22:29 UTC
The ARM version of windows does not include File History. Ran with -Debug.
<img width="1800" alt="SCR-20240825-qbyh" src="https://github.com/user-attachments/assets/75579859-d526-47a7-bf66-93929b84e0b4">
[__Script Result Statistics.zip](https://github.com/user-attachments/files/16742174/__Script.Result.Statistics.zip)

**Comment by ThioJoe** [comment] 2024-08-26 00:43
Hm that could explain the errors others have been having, I'll have to look up how it's different on ARM

**Comment by ThioJoe** [comment] 2024-08-27 22:22
This is partly fixed as of the latest commit.
Latest script version available here: https://github.com/ThioJoe/Windows-Super-God-Mode/blob/main/Super_God_Mode.ps1

It will at least stop the error from completely stopping the script if there's a problem with any of the shortcuts, but I haven't worked on the root cause for that exact error yet for that file.

**Comment by ThioJoe** [comment] 2024-08-28 23:49
Ok i believe this is fully fixed, even the other error. Checked on my Mac running windows via Parallels

**Closed by ThioJoe** 2024-08-28 23:49 UTC
Labels: Bug / Error, Partial Fix
